spring:
  config:
    import: 'classpath:application-model.yaml'
  application:
    name: feetekourse
server:
  port: 8080
  servlet:
    context-path: /fee-tekourse

logging:
  level:
    org:
      springframework:
        security: DEBUG