openapi: 3.0.3
info:
  title: Swagger  Recipe - OpenApi 3
  description: |-
   Swagger for the Recipes API
  termsOfService: http://swagger.io/terms/
  contact:
    email: raphael.henin@laposte.net
  version: 1.0
servers:
  - url: https://fee-tekourse/api/v3
tags:
  - name: recipe
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /example/{id}:
    get:
      tags:
        - recipe
      summary: Get recipe
      description: Get recipe by Id
      operationId: getRecipe
      parameters:
        - name: id
          in: path
          description: id of the recipe
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '400':
          description: Invalid ID supplied
        '404':
          description: Recipe not found
        '405':
          description: Validation exception
components:
  schemas:
    Recipe:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: doggie